/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface Erc721SerialFactoryInterface extends ethers.utils.Interface {
  functions: {
    "CREATE_SERIAL_ROLE()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "MINTER_ROLE()": FunctionFragment;
    "approve(address,uint256)": FunctionFragment;
    "balanceOf(address)": FunctionFragment;
    "createSerial(string,string,string,string,uint256,address,uint256,bool)": FunctionFragment;
    "currentSerial()": FunctionFragment;
    "getApproved(uint256)": FunctionFragment;
    "getContentIPFSCids(uint256)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getSerial(uint256)": FunctionFragment;
    "getSerialByToken(uint256)": FunctionFragment;
    "getSerialRecipient(uint256)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "isApprovedForAll(address,address)": FunctionFragment;
    "mintSerial(uint256)": FunctionFragment;
    "mintSerialAuthenticated(uint256,address)": FunctionFragment;
    "name()": FunctionFragment;
    "ownerOf(uint256)": FunctionFragment;
    "recoverERC20(address,uint256)": FunctionFragment;
    "recoverETH()": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "safeTransferFrom(address,address,uint256)": FunctionFragment;
    "setApprovalForAll(address,bool)": FunctionFragment;
    "setIPFSBase(string)": FunctionFragment;
    "setSerialPaused(uint256,bool)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "symbol()": FunctionFragment;
    "tokenIdsReserved()": FunctionFragment;
    "tokenURI(uint256)": FunctionFragment;
    "transferFrom(address,address,uint256)": FunctionFragment;
    "updateSerialRecipient(uint256,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "CREATE_SERIAL_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MINTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "balanceOf", values: [string]): string;
  encodeFunctionData(
    functionFragment: "createSerial",
    values: [
      string,
      string,
      string,
      string,
      BigNumberish,
      string,
      BigNumberish,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "currentSerial",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getApproved",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getContentIPFSCids",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSerial",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSerialByToken",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSerialRecipient",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isApprovedForAll",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintSerial",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintSerialAuthenticated",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerOf",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverERC20",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverETH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "safeTransferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setApprovalForAll",
    values: [string, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setIPFSBase", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setSerialPaused",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tokenIdsReserved",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenURI",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSerialRecipient",
    values: [BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "CREATE_SERIAL_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MINTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createSerial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentSerial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContentIPFSCids",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSerial", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSerialByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSerialRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isApprovedForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintSerial", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintSerialAuthenticated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoverERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recoverETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "safeTransferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setApprovalForAll",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIPFSBase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSerialPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokenIdsReserved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSerialRecipient",
    data: BytesLike
  ): Result;

  events: {
    "Approval(address,address,uint256)": EventFragment;
    "ApprovalForAll(address,address,bool)": EventFragment;
    "CreatedSerial(uint256)": EventFragment;
    "MintedSerial(uint256,uint256,address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "SetSerialPaused(uint256,bool)": EventFragment;
    "Transfer(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Approval"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ApprovalForAll"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CreatedSerial"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MintedSerial"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetSerialPaused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Transfer"): EventFragment;
}

export class Erc721SerialFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: Erc721SerialFactoryInterface;

  functions: {
    CREATE_SERIAL_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "CREATE_SERIAL_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "MINTER_ROLE()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "approve(address,uint256)"(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    balanceOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    createSerial(
      name: string,
      description: string,
      imageStoragePath: string,
      animationStoragePath: string,
      ethPrice: BigNumberish,
      purchaseRecipient: string,
      serialSize: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "createSerial(string,string,string,string,uint256,address,uint256,bool)"(
      name: string,
      description: string,
      imageStoragePath: string,
      animationStoragePath: string,
      ethPrice: BigNumberish,
      purchaseRecipient: string,
      serialSize: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    currentSerial(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "currentSerial()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getApproved(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getContentIPFSCids(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
    }>;

    "getContentIPFSCids(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
    }>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getSerial(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        name: string;
        description: string;
        animationStoragePath: string;
        imageStoragePath: string;
        purchaseRecipient: string;
        ethPrice: BigNumber;
        serialSize: BigNumber;
        atSerialId: BigNumber;
        paused: boolean;
        firstReservedToken: BigNumber;
        0: string;
        1: string;
        2: string;
        3: string;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: BigNumber;
        8: boolean;
        9: BigNumber;
      };
    }>;

    "getSerial(uint256)"(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        name: string;
        description: string;
        animationStoragePath: string;
        imageStoragePath: string;
        purchaseRecipient: string;
        ethPrice: BigNumber;
        serialSize: BigNumber;
        atSerialId: BigNumber;
        paused: boolean;
        firstReservedToken: BigNumber;
        0: string;
        1: string;
        2: string;
        3: string;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: BigNumber;
        8: boolean;
        9: BigNumber;
      };
    }>;

    getSerialByToken(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        name: string;
        description: string;
        animationStoragePath: string;
        imageStoragePath: string;
        purchaseRecipient: string;
        ethPrice: BigNumber;
        serialSize: BigNumber;
        atSerialId: BigNumber;
        paused: boolean;
        firstReservedToken: BigNumber;
        0: string;
        1: string;
        2: string;
        3: string;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: BigNumber;
        8: boolean;
        9: BigNumber;
      };
    }>;

    "getSerialByToken(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        name: string;
        description: string;
        animationStoragePath: string;
        imageStoragePath: string;
        purchaseRecipient: string;
        ethPrice: BigNumber;
        serialSize: BigNumber;
        atSerialId: BigNumber;
        paused: boolean;
        firstReservedToken: BigNumber;
        0: string;
        1: string;
        2: string;
        3: string;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: BigNumber;
        8: boolean;
        9: BigNumber;
      };
    }>;

    getSerialRecipient(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "getSerialRecipient(uint256)"(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "isApprovedForAll(address,address)"(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    mintSerial(
      serialId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "mintSerial(uint256)"(
      serialId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    mintSerialAuthenticated(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mintSerialAuthenticated(uint256,address)"(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "name()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "ownerOf(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    recoverERC20(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "recoverERC20(address,uint256)"(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    recoverETH(overrides?: Overrides): Promise<ContractTransaction>;

    "recoverETH()"(overrides?: Overrides): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setApprovalForAll(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setIPFSBase(
      newIpfsBaseUrl: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setIPFSBase(string)"(
      newIpfsBaseUrl: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setSerialPaused(
      serialId: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setSerialPaused(uint256,bool)"(
      serialId: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: boolean;
    }>;

    symbol(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "symbol()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    tokenIdsReserved(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "tokenIdsReserved()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    updateSerialRecipient(
      serialId: BigNumberish,
      newRecipient: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateSerialRecipient(uint256,address)"(
      serialId: BigNumberish,
      newRecipient: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  CREATE_SERIAL_ROLE(overrides?: CallOverrides): Promise<string>;

  "CREATE_SERIAL_ROLE()"(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

  MINTER_ROLE(overrides?: CallOverrides): Promise<string>;

  "MINTER_ROLE()"(overrides?: CallOverrides): Promise<string>;

  approve(
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "approve(address,uint256)"(
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

  "balanceOf(address)"(
    owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  createSerial(
    name: string,
    description: string,
    imageStoragePath: string,
    animationStoragePath: string,
    ethPrice: BigNumberish,
    purchaseRecipient: string,
    serialSize: BigNumberish,
    paused: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "createSerial(string,string,string,string,uint256,address,uint256,bool)"(
    name: string,
    description: string,
    imageStoragePath: string,
    animationStoragePath: string,
    ethPrice: BigNumberish,
    purchaseRecipient: string,
    serialSize: BigNumberish,
    paused: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  currentSerial(overrides?: CallOverrides): Promise<BigNumber>;

  "currentSerial()"(overrides?: CallOverrides): Promise<BigNumber>;

  getApproved(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getApproved(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getContentIPFSCids(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    0: string;
    1: string;
  }>;

  "getContentIPFSCids(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    0: string;
    1: string;
  }>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getRoleAdmin(bytes32)"(
    role: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getSerial(
    serialId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    name: string;
    description: string;
    animationStoragePath: string;
    imageStoragePath: string;
    purchaseRecipient: string;
    ethPrice: BigNumber;
    serialSize: BigNumber;
    atSerialId: BigNumber;
    paused: boolean;
    firstReservedToken: BigNumber;
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: BigNumber;
    6: BigNumber;
    7: BigNumber;
    8: boolean;
    9: BigNumber;
  }>;

  "getSerial(uint256)"(
    serialId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    name: string;
    description: string;
    animationStoragePath: string;
    imageStoragePath: string;
    purchaseRecipient: string;
    ethPrice: BigNumber;
    serialSize: BigNumber;
    atSerialId: BigNumber;
    paused: boolean;
    firstReservedToken: BigNumber;
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: BigNumber;
    6: BigNumber;
    7: BigNumber;
    8: boolean;
    9: BigNumber;
  }>;

  getSerialByToken(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    name: string;
    description: string;
    animationStoragePath: string;
    imageStoragePath: string;
    purchaseRecipient: string;
    ethPrice: BigNumber;
    serialSize: BigNumber;
    atSerialId: BigNumber;
    paused: boolean;
    firstReservedToken: BigNumber;
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: BigNumber;
    6: BigNumber;
    7: BigNumber;
    8: boolean;
    9: BigNumber;
  }>;

  "getSerialByToken(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<{
    name: string;
    description: string;
    animationStoragePath: string;
    imageStoragePath: string;
    purchaseRecipient: string;
    ethPrice: BigNumber;
    serialSize: BigNumber;
    atSerialId: BigNumber;
    paused: boolean;
    firstReservedToken: BigNumber;
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: BigNumber;
    6: BigNumber;
    7: BigNumber;
    8: boolean;
    9: BigNumber;
  }>;

  getSerialRecipient(
    serialId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "getSerialRecipient(uint256)"(
    serialId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "grantRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "hasRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isApprovedForAll(
    owner: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isApprovedForAll(address,address)"(
    owner: string,
    operator: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  mintSerial(
    serialId: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "mintSerial(uint256)"(
    serialId: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  mintSerialAuthenticated(
    serialId: BigNumberish,
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mintSerialAuthenticated(uint256,address)"(
    serialId: BigNumberish,
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  "name()"(overrides?: CallOverrides): Promise<string>;

  ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "ownerOf(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  recoverERC20(
    tokenAddress: string,
    tokenAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "recoverERC20(address,uint256)"(
    tokenAddress: string,
    tokenAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  recoverETH(overrides?: Overrides): Promise<ContractTransaction>;

  "recoverETH()"(overrides?: Overrides): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "renounceRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "revokeRole(bytes32,address)"(
    role: BytesLike,
    account: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "safeTransferFrom(address,address,uint256,bytes)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    _data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setApprovalForAll(
    operator: string,
    approved: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setApprovalForAll(address,bool)"(
    operator: string,
    approved: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setIPFSBase(
    newIpfsBaseUrl: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setIPFSBase(string)"(
    newIpfsBaseUrl: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setSerialPaused(
    serialId: BigNumberish,
    paused: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setSerialPaused(uint256,bool)"(
    serialId: BigNumberish,
    paused: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "supportsInterface(bytes4)"(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  symbol(overrides?: CallOverrides): Promise<string>;

  "symbol()"(overrides?: CallOverrides): Promise<string>;

  tokenIdsReserved(overrides?: CallOverrides): Promise<BigNumber>;

  "tokenIdsReserved()"(overrides?: CallOverrides): Promise<BigNumber>;

  tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "tokenURI(uint256)"(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  transferFrom(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferFrom(address,address,uint256)"(
    from: string,
    to: string,
    tokenId: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  updateSerialRecipient(
    serialId: BigNumberish,
    newRecipient: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateSerialRecipient(uint256,address)"(
    serialId: BigNumberish,
    newRecipient: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    CREATE_SERIAL_ROLE(overrides?: CallOverrides): Promise<string>;

    "CREATE_SERIAL_ROLE()"(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<string>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<string>;

    "MINTER_ROLE()"(overrides?: CallOverrides): Promise<string>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "approve(address,uint256)"(
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createSerial(
      name: string,
      description: string,
      imageStoragePath: string,
      animationStoragePath: string,
      ethPrice: BigNumberish,
      purchaseRecipient: string,
      serialSize: BigNumberish,
      paused: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "createSerial(string,string,string,string,uint256,address,uint256,bool)"(
      name: string,
      description: string,
      imageStoragePath: string,
      animationStoragePath: string,
      ethPrice: BigNumberish,
      purchaseRecipient: string,
      serialSize: BigNumberish,
      paused: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    currentSerial(overrides?: CallOverrides): Promise<BigNumber>;

    "currentSerial()"(overrides?: CallOverrides): Promise<BigNumber>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getApproved(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getContentIPFSCids(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
    }>;

    "getContentIPFSCids(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: string;
    }>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getSerial(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      name: string;
      description: string;
      animationStoragePath: string;
      imageStoragePath: string;
      purchaseRecipient: string;
      ethPrice: BigNumber;
      serialSize: BigNumber;
      atSerialId: BigNumber;
      paused: boolean;
      firstReservedToken: BigNumber;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
      8: boolean;
      9: BigNumber;
    }>;

    "getSerial(uint256)"(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      name: string;
      description: string;
      animationStoragePath: string;
      imageStoragePath: string;
      purchaseRecipient: string;
      ethPrice: BigNumber;
      serialSize: BigNumber;
      atSerialId: BigNumber;
      paused: boolean;
      firstReservedToken: BigNumber;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
      8: boolean;
      9: BigNumber;
    }>;

    getSerialByToken(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      name: string;
      description: string;
      animationStoragePath: string;
      imageStoragePath: string;
      purchaseRecipient: string;
      ethPrice: BigNumber;
      serialSize: BigNumber;
      atSerialId: BigNumber;
      paused: boolean;
      firstReservedToken: BigNumber;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
      8: boolean;
      9: BigNumber;
    }>;

    "getSerialByToken(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      name: string;
      description: string;
      animationStoragePath: string;
      imageStoragePath: string;
      purchaseRecipient: string;
      ethPrice: BigNumber;
      serialSize: BigNumber;
      atSerialId: BigNumber;
      paused: boolean;
      firstReservedToken: BigNumber;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: BigNumber;
      6: BigNumber;
      7: BigNumber;
      8: boolean;
      9: BigNumber;
    }>;

    getSerialRecipient(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "getSerialRecipient(uint256)"(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isApprovedForAll(address,address)"(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    mintSerial(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "mintSerial(uint256)"(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintSerialAuthenticated(
      serialId: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "mintSerialAuthenticated(uint256,address)"(
      serialId: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<string>;

    "name()"(overrides?: CallOverrides): Promise<string>;

    ownerOf(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "ownerOf(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    recoverERC20(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "recoverERC20(address,uint256)"(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    recoverETH(overrides?: CallOverrides): Promise<void>;

    "recoverETH()"(overrides?: CallOverrides): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setApprovalForAll(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setIPFSBase(
      newIpfsBaseUrl: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setIPFSBase(string)"(
      newIpfsBaseUrl: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setSerialPaused(
      serialId: BigNumberish,
      paused: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "setSerialPaused(uint256,bool)"(
      serialId: BigNumberish,
      paused: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    symbol(overrides?: CallOverrides): Promise<string>;

    "symbol()"(overrides?: CallOverrides): Promise<string>;

    tokenIdsReserved(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenIdsReserved()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokenURI(tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSerialRecipient(
      serialId: BigNumberish,
      newRecipient: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateSerialRecipient(uint256,address)"(
      serialId: BigNumberish,
      newRecipient: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    Approval(
      owner: string | null,
      approved: string | null,
      tokenId: BigNumberish | null
    ): EventFilter;

    ApprovalForAll(
      owner: string | null,
      operator: string | null,
      approved: null
    ): EventFilter;

    CreatedSerial(serialId: null): EventFilter;

    MintedSerial(serialId: null, tokenId: null, minter: null): EventFilter;

    RoleAdminChanged(
      role: BytesLike | null,
      previousAdminRole: BytesLike | null,
      newAdminRole: BytesLike | null
    ): EventFilter;

    RoleGranted(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): EventFilter;

    RoleRevoked(
      role: BytesLike | null,
      account: string | null,
      sender: string | null
    ): EventFilter;

    SetSerialPaused(serialId: null, isPaused: null): EventFilter;

    Transfer(
      from: string | null,
      to: string | null,
      tokenId: BigNumberish | null
    ): EventFilter;
  };

  estimateGas: {
    CREATE_SERIAL_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "CREATE_SERIAL_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "DEFAULT_ADMIN_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    "MINTER_ROLE()"(overrides?: CallOverrides): Promise<BigNumber>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "approve(address,uint256)"(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    balanceOf(owner: string, overrides?: CallOverrides): Promise<BigNumber>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createSerial(
      name: string,
      description: string,
      imageStoragePath: string,
      animationStoragePath: string,
      ethPrice: BigNumberish,
      purchaseRecipient: string,
      serialSize: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "createSerial(string,string,string,string,uint256,address,uint256,bool)"(
      name: string,
      description: string,
      imageStoragePath: string,
      animationStoragePath: string,
      ethPrice: BigNumberish,
      purchaseRecipient: string,
      serialSize: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    currentSerial(overrides?: CallOverrides): Promise<BigNumber>;

    "currentSerial()"(overrides?: CallOverrides): Promise<BigNumber>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getApproved(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getContentIPFSCids(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getContentIPFSCids(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSerial(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSerial(uint256)"(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSerialByToken(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSerialByToken(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSerialRecipient(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSerialRecipient(uint256)"(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isApprovedForAll(address,address)"(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintSerial(
      serialId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "mintSerial(uint256)"(
      serialId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    mintSerialAuthenticated(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "mintSerialAuthenticated(uint256,address)"(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    "name()"(overrides?: CallOverrides): Promise<BigNumber>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "ownerOf(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    recoverERC20(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "recoverERC20(address,uint256)"(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    recoverETH(overrides?: Overrides): Promise<BigNumber>;

    "recoverETH()"(overrides?: Overrides): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setApprovalForAll(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setIPFSBase(
      newIpfsBaseUrl: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setIPFSBase(string)"(
      newIpfsBaseUrl: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setSerialPaused(
      serialId: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setSerialPaused(uint256,bool)"(
      serialId: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    symbol(overrides?: CallOverrides): Promise<BigNumber>;

    "symbol()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokenIdsReserved(overrides?: CallOverrides): Promise<BigNumber>;

    "tokenIdsReserved()"(overrides?: CallOverrides): Promise<BigNumber>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    updateSerialRecipient(
      serialId: BigNumberish,
      newRecipient: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateSerialRecipient(uint256,address)"(
      serialId: BigNumberish,
      newRecipient: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CREATE_SERIAL_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "CREATE_SERIAL_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "DEFAULT_ADMIN_ROLE()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MINTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "MINTER_ROLE()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    approve(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "approve(address,uint256)"(
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "balanceOf(address)"(
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createSerial(
      name: string,
      description: string,
      imageStoragePath: string,
      animationStoragePath: string,
      ethPrice: BigNumberish,
      purchaseRecipient: string,
      serialSize: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "createSerial(string,string,string,string,uint256,address,uint256,bool)"(
      name: string,
      description: string,
      imageStoragePath: string,
      animationStoragePath: string,
      ethPrice: BigNumberish,
      purchaseRecipient: string,
      serialSize: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    currentSerial(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "currentSerial()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getApproved(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getApproved(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getContentIPFSCids(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getContentIPFSCids(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoleAdmin(bytes32)"(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSerial(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSerial(uint256)"(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSerialByToken(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSerialByToken(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSerialRecipient(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSerialRecipient(uint256)"(
      serialId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "grantRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "hasRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isApprovedForAll(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isApprovedForAll(address,address)"(
      owner: string,
      operator: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mintSerial(
      serialId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "mintSerial(uint256)"(
      serialId: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    mintSerialAuthenticated(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mintSerialAuthenticated(uint256,address)"(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "name()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ownerOf(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "ownerOf(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    recoverERC20(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "recoverERC20(address,uint256)"(
      tokenAddress: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    recoverETH(overrides?: Overrides): Promise<PopulatedTransaction>;

    "recoverETH()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "renounceRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revokeRole(bytes32,address)"(
      role: BytesLike,
      account: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "safeTransferFrom(address,address,uint256,bytes)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      _data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setApprovalForAll(
      operator: string,
      approved: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setApprovalForAll(address,bool)"(
      operator: string,
      approved: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setIPFSBase(
      newIpfsBaseUrl: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setIPFSBase(string)"(
      newIpfsBaseUrl: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setSerialPaused(
      serialId: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setSerialPaused(uint256,bool)"(
      serialId: BigNumberish,
      paused: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "supportsInterface(bytes4)"(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "symbol()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokenIdsReserved(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "tokenIdsReserved()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tokenURI(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "tokenURI(uint256)"(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferFrom(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferFrom(address,address,uint256)"(
      from: string,
      to: string,
      tokenId: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    updateSerialRecipient(
      serialId: BigNumberish,
      newRecipient: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateSerialRecipient(uint256,address)"(
      serialId: BigNumberish,
      newRecipient: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
