/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ISerialMintableInterface extends ethers.utils.Interface {
  functions: {
    "mintSerial(address)": FunctionFragment;
    "mintSerials(address[])": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "mintSerial", values: [string]): string;
  encodeFunctionData(
    functionFragment: "mintSerials",
    values: [string[]]
  ): string;

  decodeFunctionResult(functionFragment: "mintSerial", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintSerials",
    data: BytesLike
  ): Result;

  events: {};
}

export class ISerialMintable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ISerialMintableInterface;

  functions: {
    mintSerial(to: string, overrides?: Overrides): Promise<ContractTransaction>;

    "mintSerial(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    mintSerials(
      to: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mintSerials(address[])"(
      to: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  mintSerial(to: string, overrides?: Overrides): Promise<ContractTransaction>;

  "mintSerial(address)"(
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  mintSerials(
    to: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mintSerials(address[])"(
    to: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    mintSerial(to: string, overrides?: CallOverrides): Promise<BigNumber>;

    "mintSerial(address)"(
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintSerials(to: string[], overrides?: CallOverrides): Promise<BigNumber>;

    "mintSerials(address[])"(
      to: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    mintSerial(to: string, overrides?: Overrides): Promise<BigNumber>;

    "mintSerial(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    mintSerials(to: string[], overrides?: Overrides): Promise<BigNumber>;

    "mintSerials(address[])"(
      to: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mintSerial(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mintSerial(address)"(
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    mintSerials(
      to: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mintSerials(address[])"(
      to: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
