/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ISerialMultipleMintableInterface extends ethers.utils.Interface {
  functions: {
    "mintSerial(uint256,address)": FunctionFragment;
    "mintSerials(uint256,address[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "mintSerial",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "mintSerials",
    values: [BigNumberish, string[]]
  ): string;

  decodeFunctionResult(functionFragment: "mintSerial", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintSerials",
    data: BytesLike
  ): Result;

  events: {};
}

export class ISerialMultipleMintable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ISerialMultipleMintableInterface;

  functions: {
    mintSerial(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mintSerial(uint256,address)"(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    mintSerials(
      serialId: BigNumberish,
      to: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "mintSerials(uint256,address[])"(
      serialId: BigNumberish,
      to: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  mintSerial(
    serialId: BigNumberish,
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mintSerial(uint256,address)"(
    serialId: BigNumberish,
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  mintSerials(
    serialId: BigNumberish,
    to: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "mintSerials(uint256,address[])"(
    serialId: BigNumberish,
    to: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    mintSerial(
      serialId: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "mintSerial(uint256,address)"(
      serialId: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintSerials(
      serialId: BigNumberish,
      to: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "mintSerials(uint256,address[])"(
      serialId: BigNumberish,
      to: string[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    mintSerial(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "mintSerial(uint256,address)"(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    mintSerials(
      serialId: BigNumberish,
      to: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "mintSerials(uint256,address[])"(
      serialId: BigNumberish,
      to: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    mintSerial(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mintSerial(uint256,address)"(
      serialId: BigNumberish,
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    mintSerials(
      serialId: BigNumberish,
      to: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "mintSerials(uint256,address[])"(
      serialId: BigNumberish,
      to: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
