name: Check for storage collisions
on: [pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.2"
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - run: |
          curl -L https://foundry.paradigm.xyz | bash
          source /home/runner/.bashrc 
          yarn install 
     
      - name: "Inspect Storage Layout"
        continue-on-error: false
        id: storage-inspect-check
        run: |
          yarn storage-inspect:check
